language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.34.0  # The minimal Rust version we claim we need.
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test --verbose
cache: cargo
