[package]
name = "ber"
version = "0.1.0"
authors = [
    "Tim Bruijnzeels <tim@nlnetlabs.nl>",
    "Martin Hoffmann <martin@nlnetlabs.nl>"
]

[dependencies]
bytes           = "^0.4"
failure         = "^0.1"

[features]
# Panic when a parsing error occurs. This feature is intended for
# development use exclusively and MUST NOT be enabled in release builds.
extra-debug = []
